image: archlinux:latest

before_script:
  - pacman --noconfirm --needed -Syyu base base-devel git neovim zsh
  - useradd -m -G wheel -s /bin/zsh "$GITLAB_USER_LOGIN"
  - sed -i '/%wheel\sALL=(ALL)\sNOPASSWD:\sALL/s/^#\s//g' /etc/sudoers
  - curl -O https://raw.githubusercontent.com/khuedoan/linux-setup/master/misc/install-dotfiles.sh
  - chmod +x install-dotfiles.sh

test:
  stage: test
  script:
    - /bin/su -c "/builds/$GITLAB_USER_LOGIN/dotfiles/install-dotfiles.sh --dotfiles --aur-helper --packages --extra-packages -y" - $GITLAB_USER_LOGIN
